
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `directus_migrations` (`version` varchar(255) not null, `name` varchar(255) not null, `timestamp` datetime default CURRENT_TIMESTAMP, primary key (`version`));
INSERT INTO directus_migrations VALUES('20201028A','Remove Collection Foreign Keys','2021-11-10 05:43:55');
INSERT INTO directus_migrations VALUES('20201029A','Remove System Relations','2021-11-10 05:43:55');
INSERT INTO directus_migrations VALUES('20201029B','Remove System Collections','2021-11-10 05:43:55');
INSERT INTO directus_migrations VALUES('20201029C','Remove System Fields','2021-11-10 05:43:55');
INSERT INTO directus_migrations VALUES('20201105A','Add Cascade System Relations','2021-11-10 05:43:56');
INSERT INTO directus_migrations VALUES('20201105B','Change Webhook URL Type','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210225A','Add Relations Sort Field','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210304A','Remove Locked Fields','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210312A','Webhooks Collections Text','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210331A','Add Refresh Interval','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210415A','Make Filesize Nullable','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210416A','Add Collections Accountability','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210422A','Remove Files Interface','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210506A','Rename Interfaces','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210510A','Restructure Relations','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210518A','Add Foreign Key Constraints','2021-11-10 05:43:57');
INSERT INTO directus_migrations VALUES('20210519A','Add System Fk Triggers','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210521A','Add Collections Icon Color','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210525A','Add Insights','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210608A','Add Deep Clone Config','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210626A','Change Filesize Bigint','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210716A','Add Conditions to Fields','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210721A','Add Default Folder','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210802A','Replace Groups','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210803A','Add Required to Fields','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210805A','Update Groups','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210805B','Change Image Metadata Structure','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210811A','Add Geometry Config','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210831A','Remove Limit Column','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210903A','Add Auth Provider','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210907A','Webhooks Collections Not Null','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210910A','Move Module Setup','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210920A','Webhooks URL Not Null','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210924A','Add Collection Organization','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210927A','Replace Fields Group','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210927B','Replace M2M Interface','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20210929A','Rename Login Action','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20211007A','Update Presets','2021-11-10 05:43:58');
INSERT INTO directus_migrations VALUES('20211009A','Add Auth Data','2021-11-10 05:43:59');
INSERT INTO directus_migrations VALUES('20211016A','Add Webhook Headers','2021-11-10 05:43:59');
INSERT INTO directus_migrations VALUES('20211103A','Set Unique to User Token','2021-11-10 05:43:59');
INSERT INTO directus_migrations VALUES('20211103B','Update Special Geometry','2021-11-10 05:43:59');
INSERT INTO directus_migrations VALUES('20211104A','Remove Collections Listing','2021-11-10 05:43:59');
CREATE TABLE IF NOT EXISTS "directus_activity" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `action` varchar(45) NOT NULL, `user` char(36), `timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `ip` varchar(50) NOT NULL, `user_agent` varchar(255), `collection` varchar(64) NOT NULL, `item` varchar(255) NOT NULL, `comment` text);
CREATE TABLE IF NOT EXISTS "directus_folders" (`id` char(36) NOT NULL, `name` varchar(255) NOT NULL, `parent` char(36), PRIMARY KEY (`id`), FOREIGN KEY (`parent`) REFERENCES `directus_folders` (`id`));
CREATE TABLE IF NOT EXISTS "directus_relations" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `many_collection` varchar(64) NOT NULL, `many_field` varchar(64) NOT NULL, `one_collection` varchar(64), `one_field` varchar(64), `one_collection_field` varchar(64), `one_allowed_collections` text, `junction_field` varchar(64), `sort_field` varchar(64), `one_deselect_action` varchar(255) NOT NULL DEFAULT 'nullify');
CREATE TABLE IF NOT EXISTS "directus_revisions" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `activity` integer NOT NULL, `collection` varchar(64) NOT NULL, `item` varchar(255) NOT NULL, `data` json, `delta` json, `parent` integer, FOREIGN KEY (`parent`) REFERENCES `directus_revisions` (`id`), FOREIGN KEY (`activity`) REFERENCES `directus_activity` (`id`) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS "directus_sessions" (`token` varchar(64) NOT NULL, `user` char(36) NOT NULL, `expires` datetime NOT NULL, `ip` varchar(255), `user_agent` varchar(255), `data` json, PRIMARY KEY (`token`), FOREIGN KEY (`user`) REFERENCES `directus_users` (`id`) ON DELETE CASCADE);
CREATE TABLE `directus_dashboards` (`id` char(36), `name` varchar(255) not null, `icon` varchar(30) not null default 'dashboard', `note` text, `date_created` datetime default CURRENT_TIMESTAMP, `user_created` char(36), foreign key(`user_created`) references `directus_users`(`id`) on delete SET NULL, primary key (`id`));
CREATE TABLE `directus_panels` (`id` char(36), `dashboard` char(36) not null, `name` varchar(255), `icon` varchar(30) default 'insert_chart', `color` varchar(10), `show_header` boolean not null default '0', `note` text, `type` varchar(255) not null, `position_x` integer not null, `position_y` integer not null, `width` integer not null, `height` integer not null, `options` json, `date_created` datetime default CURRENT_TIMESTAMP, `user_created` char(36), foreign key(`dashboard`) references `directus_dashboards`(`id`) on delete CASCADE, foreign key(`user_created`) references `directus_users`(`id`) on delete SET NULL, primary key (`id`));
CREATE TABLE IF NOT EXISTS "directus_files" (`id` char(36) NOT NULL, `storage` varchar(255) NOT NULL, `filename_disk` varchar(255), `filename_download` varchar(255) NOT NULL, `title` varchar(255), `type` varchar(255), `folder` char(36), `uploaded_by` char(36), `uploaded_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `modified_by` char(36), `modified_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `charset` varchar(50), `filesize` bigint DEFAULT null, `width` integer, `height` integer, `duration` integer, `embed` varchar(200), `description` text, `location` text, `tags` text, `metadata` json, PRIMARY KEY (`id`), FOREIGN KEY (`uploaded_by`) REFERENCES `directus_users` (`id`), FOREIGN KEY (`modified_by`) REFERENCES `directus_users` (`id`), FOREIGN KEY (`folder`) REFERENCES `directus_folders` (`id`) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS "directus_settings" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `project_name` varchar(100) NOT NULL DEFAULT 'Directus', `project_url` varchar(255), `project_color` varchar(10) DEFAULT '#00C897', `project_logo` char(36), `public_foreground` char(36), `public_background` char(36), `public_note` text, `auth_login_attempts` integer DEFAULT '25', `auth_password_policy` varchar(100), `storage_asset_transform` varchar(7) DEFAULT 'all', `storage_asset_presets` json, `custom_css` text, `storage_default_folder` char(36), `basemaps` json, `mapbox_key` varchar(255), `module_bar` json, FOREIGN KEY (`project_logo`) REFERENCES `directus_files` (`id`), FOREIGN KEY (`public_foreground`) REFERENCES `directus_files` (`id`), FOREIGN KEY (`public_background`) REFERENCES `directus_files` (`id`), CONSTRAINT `directus_settings_storage_default_folder_foreign` FOREIGN KEY (`storage_default_folder`) REFERENCES `directus_folders` (`id`) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS "directus_permissions" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `role` char(36), `collection` varchar(64) NOT NULL, `action` varchar(10) NOT NULL, `permissions` json, `validation` json, `presets` json, `fields` text, FOREIGN KEY (`role`) REFERENCES `directus_roles` (`id`) ON DELETE CASCADE);
INSERT INTO directus_permissions VALUES(1,NULL,'user','create','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(2,NULL,'profile','create','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(3,NULL,'grocery_items','create','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(4,NULL,'grocery_items','read','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(5,NULL,'profile','read','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(6,NULL,'user','read','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(7,NULL,'user','update','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(8,NULL,'profile','update','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(9,NULL,'grocery_items','update','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(10,NULL,'grocery_items','delete','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(11,NULL,'profile','delete','{}','{}',NULL,'*');
INSERT INTO directus_permissions VALUES(12,NULL,'user','delete','{}','{}',NULL,'*');
CREATE TABLE IF NOT EXISTS "directus_users" (`id` char(36), `first_name` varchar(50), `last_name` varchar(50), `email` varchar(128), `password` varchar(255), `location` varchar(255), `title` varchar(50), `description` text, `tags` json, `avatar` char(36), `language` varchar(8) DEFAULT 'en-US', `theme` varchar(20) DEFAULT 'auto', `tfa_secret` varchar(255), `status` varchar(16) NOT NULL DEFAULT 'active', `role` char(36), `token` varchar(255), `last_access` datetime, `last_page` varchar(255), `provider` varchar(128) NOT NULL DEFAULT 'default', `external_identifier` varchar(255), `auth_data` json, PRIMARY KEY (`id`), FOREIGN KEY (`role`) REFERENCES `directus_roles` (`id`) ON DELETE SET NULL);
INSERT INTO directus_users VALUES('c484ffcc-4aab-471a-9046-4bf2804b63ce',NULL,NULL,'admin@grapp.org','$argon2i$v=19$m=4096,t=3,p=1$ut5gENHhaWugOI6q3WPiLg$8j7VKYRdcQbYv1hdf2YJnrTqYfNNf5zBfNFy45SR+i0',NULL,NULL,NULL,NULL,NULL,'en-US','auto',NULL,'active','04faaa89-8546-4486-b492-10156cb5b6db',NULL,NULL,NULL,'default',NULL,NULL);
CREATE TABLE IF NOT EXISTS "directus_webhooks" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` varchar(255) NOT NULL, `method` varchar(10) NOT NULL DEFAULT 'POST', `url` text NOT NULL, `status` varchar(10) NOT NULL DEFAULT 'active', `data` boolean NOT NULL DEFAULT '1', `actions` varchar(100) NOT NULL, `collections` text NOT NULL, `headers` json);
CREATE TABLE IF NOT EXISTS "directus_collections" (`collection` varchar(64), `icon` varchar(30), `note` text, `display_template` varchar(255), `hidden` boolean NOT NULL DEFAULT '0', `singleton` boolean NOT NULL DEFAULT '0', `translations` json, `archive_field` varchar(64), `archive_app_filter` boolean NOT NULL DEFAULT '1', `archive_value` varchar(255), `unarchive_value` varchar(255), `sort_field` varchar(64), `accountability` varchar(255) DEFAULT 'all', `color` varchar(255) NULL, `item_duplication_fields` json NULL, `sort` integer, `group` varchar(64), `collapse` varchar(255) NOT NULL DEFAULT 'open', PRIMARY KEY (`collection`), FOREIGN KEY (`group`) REFERENCES `directus_collections` (`collection`));
CREATE TABLE IF NOT EXISTS "directus_fields" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `collection` varchar(64) NOT NULL, `field` varchar(64) NOT NULL, `special` varchar(64), `interface` varchar(64), `options` json, `display` varchar(64), `display_options` json, `readonly` boolean NOT NULL DEFAULT '0', `hidden` boolean NOT NULL DEFAULT '0', `sort` integer, `width` varchar(30) DEFAULT 'full', `translations` json, `note` text, `conditions` json, `required` boolean DEFAULT '0', `group` varchar(64));
CREATE TABLE IF NOT EXISTS "directus_presets" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `bookmark` varchar(255), `user` char(36), `role` char(36), `collection` varchar(64), `search` varchar(100), `layout` varchar(100) DEFAULT 'tabular', `layout_query` json, `layout_options` json, `refresh_interval` integer, `filter` json, FOREIGN KEY (`user`) REFERENCES `directus_users` (`id`) ON DELETE CASCADE, FOREIGN KEY (`role`) REFERENCES `directus_roles` (`id`) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS "directus_roles" (`id` char(36), `name` varchar(100) NOT NULL, `icon` varchar(30) NOT NULL DEFAULT 'supervised_user_circle', `description` text, `ip_access` text, `enforce_tfa` boolean NOT NULL DEFAULT '0', `admin_access` boolean NOT NULL DEFAULT '0', `app_access` boolean NOT NULL DEFAULT '1', PRIMARY KEY (`id`));
INSERT INTO directus_roles VALUES('04faaa89-8546-4486-b492-10156cb5b6db','Administrator','verified','Initial administrative role with unrestricted App/API access',NULL,0,1,1);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('directus_activity',0);
INSERT INTO sqlite_sequence VALUES('directus_relations',0);
INSERT INTO sqlite_sequence VALUES('directus_revisions',0);
INSERT INTO sqlite_sequence VALUES('directus_settings',0);
INSERT INTO sqlite_sequence VALUES('directus_permissions',0);
INSERT INTO sqlite_sequence VALUES('directus_webhooks',0);
INSERT INTO sqlite_sequence VALUES('directus_fields',0);
INSERT INTO sqlite_sequence VALUES('directus_presets',0);
CREATE UNIQUE INDEX `directus_users_external_identifier_unique` on `directus_users` (`external_identifier`);
CREATE UNIQUE INDEX `directus_users_email_unique` on `directus_users` (`email`);
CREATE UNIQUE INDEX `directus_users_token_unique` on `directus_users` (`token`);

CREATE TABLE `user` (`id` integer not null primary key autoincrement, `username` varchar(255) null, `first_name` varchar(255) null, `last_name` varchar(255) null, `email` varchar(255) null);
INSERT INTO user VALUES(1,'test.user','Test','User','test.user@grapp.org');
CREATE TABLE IF NOT EXISTS "profile" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` varchar(255) NULL DEFAULT null, `user_id` integer NULL, CONSTRAINT `profile_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL);
INSERT INTO profile VALUES(1,'current',1);
INSERT INTO profile VALUES(2,'jest',1);

CREATE TABLE IF NOT EXISTS "grocery_items" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` varchar(255) NULL, `quantity` integer NULL, `unit` varchar(255) NULL, `item_type` varchar(255) NULL, `profile` integer NULL, CONSTRAINT `grocery_items_profile_foreign` FOREIGN KEY (`profile`) REFERENCES `profile` (`id`) ON DELETE SET NULL);
INSERT INTO grocery_items VALUES(1,'name1', 'quantity1', 'unit1', 'dc', 2);
INSERT INTO grocery_items VALUES(2,'name2', 'quantity2', 'unit2', 'dc', 2);
INSERT INTO grocery_items VALUES(3,'name3', 'quantity3', 'unit3', 'dc', 2);
INSERT INTO grocery_items VALUES(4,'name4', 'quantity4', 'unit4', 'dc', 2);
INSERT INTO grocery_items VALUES(5,'name5', 'quantity5', 'unit5', 'dc', 2);

COMMIT;
.quit